/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class RemMath */

#ifndef _Included_RemMath
#define _Included_RemMath
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     RemMath
 * Method:    sum_two_ints32
 * Signature: ([I[ILjava/lang/String;)[I
 */
JNIEXPORT jintArray JNICALL Java_RemMath_sum_1two_1ints32
  (JNIEnv *, jclass, jintArray, jintArray, jstring);

#ifdef __cplusplus
}
#endif
#endif
